In [1]:
import pandas as pd
import string
import nltk
from nltk.tokenize import word_tokenize
import re
import sys
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [2]:
datasmote= pd.read_csv("E:\KULIAH\TUGAS AKHIR LJ\FULL TWEET\DATA UNTUK BRI TANPA REPLIES\data smote.csv", engine="python")
datasmoteX= pd.read_csv("E:\KULIAH\TUGAS AKHIR LJ\FULL TWEET\DATA UNTUK BRI TANPA REPLIES\data smote X.csv", engine="python")
Ysmote = datasmote['class'] 
Y_nyasmote = pd.DataFrame(Ysmote) 

In [3]:
X_nyasmote = pd.DataFrame(datasmoteX)

In [4]:
#Klasifikasi
import numpy 
import numpy as np 
import matplotlib as mpl 
import matplotlib.pyplot as plt  
import optunity 
import optunity.metrics 
from scipy import stats
import sklearn
from sklearn.metrics import classification_report, confusion_matrix 
from __future__ import print_function 
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, KFold, ShuffleSplit, StratifiedShuffleSplit, RepeatedStratifiedKFold 
from sklearn.feature_selection import SelectPercentile, f_classif 
from sklearn.naive_bayes import BernoulliNB 
from sklearn.svm import LinearSVC, SVC 
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import GridSearchCV 
from sklearn.metrics import classification_report, accuracy_score 
from sklearn.utils import shuffle 
from sklearn import svm, datasets 
from sklearn.metrics import roc_curve, auc 
from scipy import interp 
from imblearn.over_sampling import SMOTE 
from sklearn import metrics 
import sklearn.svm 

In [5]:
Y_new = pd.DataFrame.as_matrix(Y_nyasmote)
X_new, Y_new = pd.DataFrame.as_matrix(datasmoteX), Y_new 

C:\Users\fasha\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
C:\Users\fasha\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [8]:
#Regresi Logistik Biner
kfold= StratifiedKFold(n_splits=4, shuffle=True)  
kfold.get_n_splits(X_new) 
kfold.get_n_splits(Y_new)
lr= LogisticRegression() 
akurasi=[]

for train, test in kfold.split(X_new, Y_new): 
            (X_new[train], X_new[test])
            (Y_new[train], Y_new[test])
            hitung = lr.fit(X_new[train], Y_new[train])
            predictrbl1 = lr.predict(X_new[train])
            predictrbl = lr.predict(X_new[test])
            fpr1, tpr1, _1 = metrics.roc_curve(Y_new[train], predictrbl1)
            fpr, tpr, _ = metrics.roc_curve(Y_new[test], predictrbl)  
            auc_1 = metrics.auc(fpr1,tpr1)
            auc_ = metrics.auc(fpr,tpr) 
            print("\nConfusiion Matrix Train: \n", metrics.confusion_matrix(Y_new[train], predictrbl1))
            print("\nConfusiion Matrix Test: \n", metrics.confusion_matrix(Y_new[test], predictrbl))
            akurasi.append(accuracy_score(Y_new[train], predictrbl1))
            akurasi.append(accuracy_score(Y_new[test], predictrbl))
            print("Akurasi Prediksi Train: ", accuracy_score(Y_new[train], predictrbl1))
            print("Akurasi Prediksi Test: ", accuracy_score(Y_new[test], predictrbl))
            print()
            print(metrics.classification_report(Y_new[train], predictrbl1))
            print(metrics.classification_report(Y_new[test], predictrbl))
            print("AUC Train: ", auc_1)
            print("AUC Test: ", auc_)


Confusiion Matrix Train: 
 [[338   0]
 [  4 332]]

Confusiion Matrix Test: 
 [[113   0]
 [  4 108]]
Akurasi Prediksi Train:  0.9940652818991098
Akurasi Prediksi Test:  0.9822222222222222

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       338
           1       1.00      0.99      0.99       336

   micro avg       0.99      0.99      0.99       674
   macro avg       0.99      0.99      0.99       674
weighted avg       0.99      0.99      0.99       674

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       113
           1       1.00      0.96      0.98       112

   micro avg       0.98      0.98      0.98       225
   macro avg       0.98      0.98      0.98       225
weighted avg       0.98      0.98      0.98       225

AUC Train:  0.9940476190476191
AUC Test:  0.9821428571428572

Confusiion Matrix Train: 
 [[338   0]
 [  8 328]]

Confusiion Matrix Test: 
 [[113   0]
 [  1 1

In [11]:
#NBC 
kfold= StratifiedKFold(n_splits=4, shuffle=True)  
kfold.get_n_splits(X_new) 
kfold.get_n_splits(Y_new)
cl = BernoulliNB() 
akurasi = []

for train, test in kfold.split(X_new, Y_new): 
            (X_new[train], X_new[test])
            (Y_new[train], Y_new[test])
            hitung = cl.fit(X_new[train], Y_new[train])     
            predictnbc1 = cl.predict(X_new[train])
            predictnbc = cl.predict(X_new[test])
            fpr1, tpr1, _1 = metrics.roc_curve(Y_new[train], predictnbc1)
            fpr, tpr, _ = metrics.roc_curve(Y_new[test], predictnbc)  
            auc_1 = metrics.auc(fpr1,tpr1)
            auc_ = metrics.auc(fpr,tpr) 
            print("\nConfusiion Matrix Train: \n", metrics.confusion_matrix(Y_new[train], predictnbc1))
            print("\nConfusiion Matrix Test: \n", metrics.confusion_matrix(Y_new[test], predictnbc))
            akurasi.append(accuracy_score(Y_new[train], predictnbc1))
            akurasi.append(accuracy_score(Y_new[test], predictnbc))
            print("Akurasi Prediksi Train: ", accuracy_score(Y_new[train], predictnbc1))
            print("Akurasi Prediksi Test: ", accuracy_score(Y_new[test], predictnbc))
            print()
            print(metrics.classification_report(Y_new[train], predictnbc1))
            print(metrics.classification_report(Y_new[test], predictnbc))
            print("AUC Train: ", auc_1)
            print("AUC Test: ", auc_)


Confusiion Matrix Train: 
 [[335   3]
 [  5 331]]

Confusiion Matrix Test: 
 [[112   1]
 [  1 111]]
Akurasi Prediksi Train:  0.9881305637982196
Akurasi Prediksi Test:  0.9911111111111112

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       338
           1       0.99      0.99      0.99       336

   micro avg       0.99      0.99      0.99       674
   macro avg       0.99      0.99      0.99       674
weighted avg       0.99      0.99      0.99       674

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       113
           1       0.99      0.99      0.99       112

   micro avg       0.99      0.99      0.99       225
   macro avg       0.99      0.99      0.99       225
weighted avg       0.99      0.99      0.99       225

AUC Train:  0.9881216539870386
AUC Test:  0.9911109355246523

Confusiion Matrix Train: 
 [[334   4]
 [  5 331]]

Confusiion Matrix Test: 
 [[113   0]
 [  3 1

In [14]:
#SVM Kernel Linear 
kfold= StratifiedKFold(n_splits=4, shuffle=True)  
kfold.get_n_splits(X_new) 
kfold.get_n_splits(Y_new)
lne= SVC(C=0.1, kernel='linear') 
akurasi = []

for train, test in kfold.split(X_new, Y_new): 
            (X_new[train], X_new[test])
            (Y_new[train], Y_new[test])
            hitung = lne.fit(X_new[train], Y_new[train])     
            predictlne1 = lne.predict(X_new[train])
            predictlne = lne.predict(X_new[test])
            fpr1, tpr1, _1 = metrics.roc_curve(Y_new[train], predictlne1)
            fpr, tpr, _ = metrics.roc_curve(Y_new[test], predictlne)  
            auc_1 = metrics.auc(fpr1,tpr1)
            auc_ = metrics.auc(fpr,tpr) 
            print("\nConfusiion Matrix Train: \n", metrics.confusion_matrix(Y_new[train], predictlne1))
            print("\nConfusiion Matrix Test: \n", metrics.confusion_matrix(Y_new[test], predictlne))
            akurasi.append(accuracy_score(Y_new[train], predictlne1))
            akurasi.append(accuracy_score(Y_new[test], predictlne))
            print("Akurasi Prediksi Train: ", accuracy_score(Y_new[train], predictlne1))
            print("Akurasi Prediksi Test: ", accuracy_score(Y_new[test], predictlne))
            print()
            print(metrics.classification_report(Y_new[train], predictlne1))
            print(metrics.classification_report(Y_new[test], predictlne))
            print("AUC Train: ", auc_1)
            print("AUC Test: ", auc_)


Confusiion Matrix Train: 
 [[336   2]
 [ 10 326]]

Confusiion Matrix Test: 
 [[112   1]
 [  6 106]]
Akurasi Prediksi Train:  0.9821958456973294
Akurasi Prediksi Test:  0.9688888888888889

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       338
           1       0.99      0.97      0.98       336

   micro avg       0.98      0.98      0.98       674
   macro avg       0.98      0.98      0.98       674
weighted avg       0.98      0.98      0.98       674

              precision    recall  f1-score   support

           0       0.95      0.99      0.97       113
           1       0.99      0.95      0.97       112

   micro avg       0.97      0.97      0.97       225
   macro avg       0.97      0.97      0.97       225
weighted avg       0.97      0.97      0.97       225

AUC Train:  0.9821604677373909
AUC Test:  0.9687895069532237

Confusiion Matrix Train: 
 [[338   0]
 [ 11 325]]

Confusiion Matrix Test: 
 [[113   0]
 [  2 1

In [17]:
#SVM Kernel RBF
kfold= StratifiedKFold(n_splits=4, shuffle=True)  
kfold.get_n_splits(X_new) 
kfold.get_n_splits(Y_new)
rbf= SVC(C=100, gamma=0.01, kernel='rbf')
akurasi = []
for train, test in kfold.split(X_new, Y_new): 
            (X_new[train], X_new[test])
            (Y_new[train], Y_new[test])
            hitung = rbf.fit(X_new[train], Y_new[train])     
            predictrbf1 = rbf.predict(X_new[train])
            predictrbf = rbf.predict(X_new[test])
            fpr1, tpr1, _1 = metrics.roc_curve(Y_new[train], predictrbf1)
            fpr, tpr, _ = metrics.roc_curve(Y_new[test], predictrbf)  
            auc_1 = metrics.auc(fpr1,tpr1)
            auc_ = metrics.auc(fpr,tpr) 
            print("\nConfusiion Matrix Train: \n", metrics.confusion_matrix(Y_new[train], predictrbf1))
            print("\nConfusiion Matrix Test: \n", metrics.confusion_matrix(Y_new[test], predictrbf))
            akurasi.append(accuracy_score(Y_new[train], predictrbf1))
            akurasi.append(accuracy_score(Y_new[test], predictrbf))
            print("Akurasi Prediksi Train: ", accuracy_score(Y_new[train], predictrbf1))
            print("Akurasi Prediksi Test: ", accuracy_score(Y_new[test], predictrbf))
            print()
            print(metrics.classification_report(Y_new[train], predictrbf1))
            print(metrics.classification_report(Y_new[test], predictrbf))
            print("AUC Train: ", auc_1)
            print("AUC Test: ", auc_)


Confusiion Matrix Train: 
 [[338   0]
 [  1 335]]

Confusiion Matrix Test: 
 [[113   0]
 [  2 110]]
Akurasi Prediksi Train:  0.9985163204747775
Akurasi Prediksi Test:  0.9911111111111112

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       338
           1       1.00      1.00      1.00       336

   micro avg       1.00      1.00      1.00       674
   macro avg       1.00      1.00      1.00       674
weighted avg       1.00      1.00      1.00       674

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       113
           1       1.00      0.98      0.99       112

   micro avg       0.99      0.99      0.99       225
   macro avg       0.99      0.99      0.99       225
weighted avg       0.99      0.99      0.99       225

AUC Train:  0.9985119047619048
AUC Test:  0.9910714285714286

Confusiion Matrix Train: 
 [[338   0]
 [  2 334]]

Confusiion Matrix Test: 
 [[113   0]
 [  1 1